[book]
authors = [
    "Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>",
]
language = "en"
multilingual = false
src = "src"
title = "Higher-Kinded Types: a magical journey dancing with lifetimes"

[rust]
edition = "2021"   # the default edition for code blocks

[output.html]
fold.enable = true
playground.editable = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
